title: Hello, world! I'm JunPyoPark
description: > # this means to ignore newlines until "baseurl:"
  Welcome to JP's Blog
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://junpyopark.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: JunPyo Park # add your name
author-img: JP.jpg # add your photo
about-author: "ğŸš¶Homo Viator<br>ğŸ“UNIST, KAIST<br>ğŸ‘¨ğŸ»â€ğŸ’»GCU Medicine"
social-twitter: # add your Twitter handle
social-instagram: ticket.park # add your Instagram handle
social-github: JunPyoPark # add your Github handle
social-linkedin: junpyopark # add your Linkedin handle
social-email: given_ticket@outlook.kr # add your Email address

# SEO Settings
lang: ko_KR
timezone: Asia/Seoul

# Disqus
discus-identifier: mr-JP # add your discus identifier

# Tracker
analytics: UA-121651076-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# SEO Plugin settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "JunPyo Park"
